import { build } from 'esbuild';
import { mkdirSync, writeFileSync } from 'node:fs';
const result = await build({entryPoints:['preview.ts'], bundle:true, write:false, format:'iife', minify:true});
const widget = (title, rows) => `<div class="fkp_dashboard-page__widgets-section__item"><b class="fkp_dashboard-page__widgets-section__item__title">${title}</b>${rows.map(([key,value])=>`<div class="fkp_dashboard-page__widgets-section__item__row"><span class="fkp_dashboard-page__widgets-section__item__row__key">${key}</span><span class="fkp_dashboard-page__widgets-section__item__row__value">${value}</span></div>`).join('')}</div>`;
const nodes = [['🇩🇪','Frankfurt · основной','VLESS · Reality','34'],['🇫🇮','Helsinki · резервный','Trojan · TLS','52'],['🇳🇱','Amsterdam','Hysteria 2','61'],['🇸🇪','Stockholm','Shadowsocks','74'],['🇫🇷','Paris','VLESS · XHTTP','81'],['🇬🇧','London','VLESS · Reality','93'],['🇺🇸','New York','Trojan · TLS','142'],['🇯🇵','Tokyo','VLESS · Reality','188']];
const cards = nodes.map(([flag,name,type,ping],index)=>`<div class="fkp_dashboard-page__outbound-grid__item ${index===0?'fkp_dashboard-page__outbound-grid__item--active':''}"><div class="fkp_dashboard-page__outbound-grid__item__header"><b>${flag} ${name}</b></div><div class="fkp_dashboard-page__outbound-grid__item__footer"><span class="fkp_dashboard-page__outbound-grid__item__type">${type}</span><span class="fkp_dashboard-page__outbound-grid__item__latency--green">${ping} мс</span></div></div>`).join('');
const html = `<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Routeflow — предпросмотр</title><style>body{margin:0;background:#e8edf3;font:14px system-ui}main{max-width:1260px;margin:38px auto;padding:0 20px}.demo{color:#53647a;margin:0 0 16px;font-size:13px}b{display:block}*{box-sizing:border-box}@media(max-width:700px){main{margin:16px auto;padding:0 10px}}</style><main><p class="demo">ПРЕДПРОСМОТР · Данные демонстрационные, соединения с роутером нет. Работают поиск, темы и плотность.</p><div id="cbi-forkop"><h2>Панель управления</h2><div class="cbi-map-descr">Подключения, маршруты и состояние сети в одном месте.</div><div class="fkp_dashboard-page"><div class="fkp_dashboard-page__content"><div class="fkp_dashboard-page__widgets-section">${widget('Трафик',[['↓ Загрузка','8,42 МБ/с'],['↑ Отправка','1,06 МБ/с']])}${widget('За сессию',[['Получено','2,8 ГБ'],['Отправлено','412 МБ']])}${widget('Роутер',[['Модель','Cudy TR3000'],['Платформа','OpenWrt 25']])}${widget('Службы',[['Forkop','Пример: запущен'],['sing-box','Пример: запущен']])}</div><section class="fkp_dashboard-page__outbound-section"><div class="fkp_dashboard-page__outbound-section__title-section"><b class="fkp_dashboard-page__outbound-section__title-section__title">Мои подключения</b><span>8 узлов · пример подписки</span></div><div class="fkp_dashboard-page__outbound-grid">${cards}</div></section><section class="fkp_dashboard-page__outbound-section"><b class="fkp_dashboard-page__outbound-section__title-section__title">Правила маршрутизации</b><p style="color:var(--rf-muted);line-height:1.8">В устанавливаемом интерфейсе доступны штатные разделы Forkop: правила, подписки, DNS, диагностика, мониторинг и обновления. В этом файле показаны только стили панели.</p></section></div></div></div></main><script>${result.outputFiles[0].text.replaceAll('</script','<\\/script')}</script></html>`;
mkdirSync('../../../outputs', {recursive:true});
writeFileSync('../../../outputs/routeflow-preview.html',html);
